version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vuhoangquan2004
      MYSQL_DATABASE: shoppc
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: shoppc_api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=shoppc;user=root;password=vuhoangquan2004;
    ports:
      - "5000:8080"
    restart: always
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
