// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopPC.Data;

#nullable disable

namespace ShopPC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104060157_AddIsSerialToProducts")]
    partial class AddIsSerialToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ShopPC.Models.Account", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("accountImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("roleName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopPC.Models.Attributes", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubCategoryid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("attributeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("categoryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("SubCategoryid");

                    b.HasIndex("categoryId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("ShopPC.Models.Brand", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ShopPC.Models.Cart", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("accountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("accountId");

                    b.HasIndex("productId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ShopPC.Models.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("iconImg")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShopPC.Models.Comment", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("accountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("accountId");

                    b.HasIndex("productId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ShopPC.Models.InvalidatedToken", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("InvalidatedTokens");
                });

            modelBuilder.Entity("ShopPC.Models.Notification", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("accountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("accountId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ShopPC.Models.Order", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("accountId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("accountId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ShopPC.Models.OrderDetail", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("ShopPC.Models.PaymentLogs", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("transactionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("ShopPC.Models.PcBuildItem", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("pcBuildId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pcBuildId");

                    b.HasIndex("productId");

                    b.ToTable("PcBuildItems");
                });

            modelBuilder.Entity("ShopPC.Models.ProductAttribute", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("attributeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("attributeId");

                    b.HasIndex("productId");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("ShopPC.Models.ProductImg", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("imgUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("ProductImg");
                });

            modelBuilder.Entity("ShopPC.Models.ProductUnit", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("imei")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("serialNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("imei")
                        .IsUnique();

                    b.HasIndex("productId");

                    b.HasIndex("serialNumber")
                        .IsUnique();

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("ShopPC.Models.Products", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("brandId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("categoryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isSerial")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("stockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("subCategoryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("thumbnail")
                        .HasColumnType("longtext");

                    b.Property<int?>("warrantyPeriod")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.HasIndex("categoryId");

                    b.HasIndex("subCategoryId");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ShopPC.Models.Report", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("accountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("accountId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("ShopPC.Models.Role", b =>
                {
                    b.Property<string>("roleName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("roleName");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            roleName = "ADMIN",
                            description = "Quản trị hệ thống"
                        },
                        new
                        {
                            roleName = "USER",
                            description = "Người dùng thông thường"
                        });
                });

            modelBuilder.Entity("ShopPC.Models.SubCategory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("categoryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("subCategoryImg")
                        .HasColumnType("longtext");

                    b.Property<string>("subCategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("ShopPC.Models.WarrantyRecord", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productUnitId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.HasIndex("productUnitId")
                        .IsUnique();

                    b.ToTable("WarrantyRecords");
                });

            modelBuilder.Entity("ShopPC.Models.WarrantyUpdateLog", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("expiredCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("WarrantyUpdateLogs");
                });

            modelBuilder.Entity("ShopPC.Models.PcBuild", b =>
                {
                    b.HasBaseType("ShopPC.Models.Products");

                    b.ToTable("PcBuild", (string)null);
                });

            modelBuilder.Entity("ShopPC.Models.Account", b =>
                {
                    b.HasOne("ShopPC.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("roleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShopPC.Models.Attributes", b =>
                {
                    b.HasOne("ShopPC.Models.SubCategory", null)
                        .WithMany("attributes")
                        .HasForeignKey("SubCategoryid");

                    b.HasOne("ShopPC.Models.Category", "category")
                        .WithMany("attributes")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("ShopPC.Models.Cart", b =>
                {
                    b.HasOne("ShopPC.Models.Account", "account")
                        .WithMany("carts")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("carts")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.Comment", b =>
                {
                    b.HasOne("ShopPC.Models.Account", "account")
                        .WithMany("comments")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("comments")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.Notification", b =>
                {
                    b.HasOne("ShopPC.Models.Account", "account")
                        .WithMany("notifications")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("ShopPC.Models.Order", b =>
                {
                    b.HasOne("ShopPC.Models.Account", "account")
                        .WithMany("orders")
                        .HasForeignKey("accountId");

                    b.Navigation("account");
                });

            modelBuilder.Entity("ShopPC.Models.OrderDetail", b =>
                {
                    b.HasOne("ShopPC.Models.Order", "order")
                        .WithMany("orderDetails")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("orderDetails")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.PcBuildItem", b =>
                {
                    b.HasOne("ShopPC.Models.PcBuild", "pcBuild")
                        .WithMany("pcBuildItem")
                        .HasForeignKey("pcBuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("pcBuildItems")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pcBuild");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.ProductAttribute", b =>
                {
                    b.HasOne("ShopPC.Models.Attributes", "attribute")
                        .WithMany("productAttributes")
                        .HasForeignKey("attributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("productAttributes")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("attribute");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.ProductImg", b =>
                {
                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("productImgs")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.ProductUnit", b =>
                {
                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("productUnits")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("ShopPC.Models.Products", b =>
                {
                    b.HasOne("ShopPC.Models.Brand", "brand")
                        .WithMany("products")
                        .HasForeignKey("brandId");

                    b.HasOne("ShopPC.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.SubCategory", "subCategory")
                        .WithMany("products")
                        .HasForeignKey("subCategoryId");

                    b.Navigation("brand");

                    b.Navigation("category");

                    b.Navigation("subCategory");
                });

            modelBuilder.Entity("ShopPC.Models.Report", b =>
                {
                    b.HasOne("ShopPC.Models.Account", "account")
                        .WithMany("reports")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("ShopPC.Models.SubCategory", b =>
                {
                    b.HasOne("ShopPC.Models.Category", "category")
                        .WithMany("subCategories")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("ShopPC.Models.WarrantyRecord", b =>
                {
                    b.HasOne("ShopPC.Models.Order", "order")
                        .WithMany("warrantyRecords")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.Products", "product")
                        .WithMany("warrantyRecords")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopPC.Models.ProductUnit", "productUnit")
                        .WithOne("warrantyRecord")
                        .HasForeignKey("ShopPC.Models.WarrantyRecord", "productUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");

                    b.Navigation("productUnit");
                });

            modelBuilder.Entity("ShopPC.Models.PcBuild", b =>
                {
                    b.HasOne("ShopPC.Models.Products", null)
                        .WithOne()
                        .HasForeignKey("ShopPC.Models.PcBuild", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopPC.Models.Account", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("comments");

                    b.Navigation("notifications");

                    b.Navigation("orders");

                    b.Navigation("reports");
                });

            modelBuilder.Entity("ShopPC.Models.Attributes", b =>
                {
                    b.Navigation("productAttributes");
                });

            modelBuilder.Entity("ShopPC.Models.Brand", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("ShopPC.Models.Category", b =>
                {
                    b.Navigation("attributes");

                    b.Navigation("products");

                    b.Navigation("subCategories");
                });

            modelBuilder.Entity("ShopPC.Models.Order", b =>
                {
                    b.Navigation("orderDetails");

                    b.Navigation("warrantyRecords");
                });

            modelBuilder.Entity("ShopPC.Models.ProductUnit", b =>
                {
                    b.Navigation("warrantyRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("ShopPC.Models.Products", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("comments");

                    b.Navigation("orderDetails");

                    b.Navigation("pcBuildItems");

                    b.Navigation("productAttributes");

                    b.Navigation("productImgs");

                    b.Navigation("productUnits");

                    b.Navigation("warrantyRecords");
                });

            modelBuilder.Entity("ShopPC.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ShopPC.Models.SubCategory", b =>
                {
                    b.Navigation("attributes");

                    b.Navigation("products");
                });

            modelBuilder.Entity("ShopPC.Models.PcBuild", b =>
                {
                    b.Navigation("pcBuildItem");
                });
#pragma warning restore 612, 618
        }
    }
}
